# Generated by Django 5.0.4 on 2024-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0002_command"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
