# Generated by Django 5.0.4 on 2024-04-23 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0004_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
