# Generated by Django 5.0.4 on 2024-04-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0005_remove_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product/"),
        ),
    ]
