# Generated by Django 5.0.4 on 2024-04-24 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0006_alter_product_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
