# Generated by Django 5.0.4 on 2024-04-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0008_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Category",
            field=models.CharField(
                choices=[
                    ("GC", "Games De Chere"),
                    ("PI", "Produit vendu individuellement"),
                ],
                default="GC",
                max_length=50,
            ),
        ),
    ]
