# Generated by Django 5.0.4 on 2024-04-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0009_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Category",
            field=models.CharField(
                choices=[
                    ("GC", "Games De Chere"),
                    ("PI", "Produit vendu individuellement"),
                    ("autres", "Autres"),
                    ("Populaire", "populaire"),
                ],
                default="Populaire",
                max_length=50,
            ),
        ),
    ]
