# Generated by Django 5.0.4 on 2024-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0012_rename_stok_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="popular_products",
            field=models.BooleanField(default=False),
        ),
    ]
